### Feth All Tasks
GET http://localhost:5000/tasks
Content-Type: application/json


### Create a New Task
POST http://localhost:5000/tasks
Content-Type: application/json
{
 "title": "This is a Title-2",
 "date": "05/12/2022",
 "description": "This is a Description-2",
 "priority": "normal",
 "status": "todo"
}


###Update A Task
PUT http://localhost:5000/tasks
Content-Type: application/json
{
 "id": "1",
 "status": "inProgress"
}